- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Ensure apt-transport-https and curl are installed
  apt:
    name:
      - apt-transport-https
      - curl
    state: present

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes signing key
  command: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key -o /tmp/Release.key
  args:
    creates: /tmp/Release.key

- name: Convert Kubernetes signing key to gpg format
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  copy:
    content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache
  apt:
    update_cache: yes


- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: yes

- name: Initialize Kubernetes Master
  shell: |
    kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=192.168.0.0/16
  when: inventory_hostname == "192.168.0.129"
  become: yes

- name: Set up kubeconfig for root
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  when: inventory_hostname == "192.168.0.129"
  become: yes

- name: Install Calico network plugin
  shell: |
    kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  when: inventory_hostname == "192.168.0.129"
  become: yes

- name: Generate join command on master
  shell: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname == "192.168.0.129"
  become: yes

- name: Save join command to a file on master
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/kubeadm_join_command.sh
  when: inventory_hostname == "192.168.0.129"
  become: yes

- name: Ensure join command file exists
  stat:
    path: /tmp/kubeadm_join_command.sh
  register: join_command_file
  when: inventory_hostname == "192.168.0.129"
  become: yes

- name: Set proper permissions on join command file
  file:
    path: /tmp/kubeadm_join_command.sh
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "192.168.0.129" and join_command_file.stat.exists
  become: yes

- name: Debug join command file status
  debug:
    var: join_command_file
  when: inventory_hostname == "192.168.0.129"

- name: Copy join command file from master to worker nodes
  copy:
    src: /tmp/kubeadm_join_command.sh
    dest: /tmp/kubeadm_join_command.sh
    remote_src: yes
  delegate_to: 192.168.0.129
  when: inventory_hostname != "192.168.0.129"
  become: yes

- name: Join worker nodes to cluster
  shell: bash /tmp/kubeadm_join_command.sh
  when: inventory_hostname != "192.168.0.129"
  become: yes
