# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-pod-name-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-pod-name
  template:
    metadata:
      labels:
        app: print-pod-name
    spec:
      containers:
      - name: print-pod-name-container
        image: asia-southeast1-docker.pkg.dev/fit-hub-staging/test/print-pod-name:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: print-pod-name-service
spec:
  selector:
    app: print-pod-name
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
