---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test3
spec:
  secretName: test3-tls
  issuerRef:
    kind: ClusterIssuer
    name: cloud-dns-issuer
  dnsNames:
  - test.svc.staging.fithubdev.com