# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: cloud-dns-issuer
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: cloud-dns-issuer-key
#     solvers:
#     - dns01:
#         cloudDNS:
#           project: fit-hub-staging
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloud-dns-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloud-dns-issuer-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
